services:
  - type: web
    name: moodtunes-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    plan: free
    rootDir: backend
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000

  - type: web
    name: moodtunes-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    plan: free
    rootDir: ./
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          type: web
          name: moodtunes-backend
          property: host
